[package]
name = "rustcv"
version = "0.1.0"
authors = ["cog", "Nickiel"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#image-rs and nalgebra
image = "0.23"
